auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka:29092
    name: local-cluster
    properties: {}
    readOnly: false
  - bootstrapServers: kafka:9092
    name: sagdemo
    properties: {}
    readOnly: false
rbac:
  roles: []
webclient: {}
